### ISSUE TITLE
lix-demo-node: modularization (refactoring)

### ISSUE THREAD

**Issue by idleherb** [agareis/coding-journey#11]
- separate server request / response handling and actual business logic (readability calculation):
  - create a separate module 'readability.js' that exports one function to compute the readability of a text
  - the module also includes helper functions like getLongWordsCount, but they do not get exposed (private)
  - app.js then imports that one function and uses it as "middleware"

Quick read: http://openmymind.net/2012/2/3/Node-Require-and-Exports/
In-depth: https://medium.freecodecamp.com/requiring-modules-in-node-js-everything-you-need-to-know-e7fbd119be8

**Comment by agareis** [comment]
@idleherb Have I already achieved the state of private helper functions to close the issue? I'm not pretty sure :/ ...

**Comment by idleherb** [comment]
@agareis move all the require(...) to the beginning of the module and you can close ;)
