### ISSUE TITLE
lix-demo-client-server: change frontend logic

### ISSUE THREAD

**Issue by idleherb** [agareis/coding-journey#13]
Add a button and only send readability calculation requests when the button is clicked

**Comment by idleherb** [comment]
@agareis https://developer.mozilla.org/de/docs/Web/HTML/Element/output suggests that the `<output>` tag should only be used together with a `<form>` tag. Replace by `<div>`.

**Comment by agareis** [comment]
@idleherb: ooouhhh ... cleaner to work I have to :D!!!
