### ISSUE TITLE
New Project: Flesch-Kincaid Grade Level

### ISSUE THREAD

**Issue by idleherb** [agareis/coding-journey#16]
- create a new folder with two files:
  readability.js (a nodejs module containing the implementation of the score)
  readability.spec.js (the corresponding tests)
- use existing nodejs-library to compute the score for an English text
- your tests should cover various input cases

**Comment by agareis** [comment]
@idleherb Q1: "use existing nodejs-library to compute the score for an English text" -> I reuse the existing library like last time by copying the filesystem into the new folder or do you have something different in mind?
