### ISSUE TITLE
lix on nodejs express

### ISSUE THREAD

**Issue by idleherb** [agareis/coding-journey#6]
prerequisite: repository refactoring issue solved

task: create express server to compute lix score on server
details:
 - server should expose one single POST endpoint /api/v1/readability
 - the "input" (body) of the post request should be a string (the text)
 - the "output" (body) of the post response should be a string (the readability statement)

NO FRONTEND (HTML) for the moment, we only want to implement the server.

**Comment by idleherb** [comment]
Looks good, great work! :)

**Comment by agareis** [comment]
Thanx :D!!!
