### ISSUE TITLE
lix-demo-node: package.json

### ISSUE THREAD

**Issue by idleherb** [agareis/coding-journey#9]
- add missing library to package.json (body-parser): hint - when installing packages in your projects, always do it using "npm install --save <package-name>"
- add start script in package.json - app should be runnable using "npm start" (see https://docs.npmjs.com/misc/scripts)
- add prestart script in package.json, should contain "npm install"

**Comment by idleherb** [comment]
@agareis Why did you add "connect" in the package.json dependencies? I don't see it being required in app.js.

**Comment by agareis** [comment]
No, you are right no need for this. Just in case! So since in the connect lib the body-parser is part of it. Somehow the body-parser dependency has interfered with the connect middleware lib dependency. This is my assumption for the bug in the app. I excluded every other possibility.
